version: "3"
services:
  application:
    image: rps.jar
    ports:
      - 8181:8080

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"